### ISSUE TITLE
test

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#1]
tescik

**Comment by baskap** [comment]
Wez jeszcze powstawiaj jakies komentarze, ok

**Comment by szelma007** [comment]
Ale jako nowe czy do tego kilka dopisać?

**Comment by baskap** [comment]
Mozesz kilka stworzyc, ale tak ze 2 i podopisywac ze dwie notatki a takze pozamykac i pootwierac.
Ja chce poprzegladac jakie dostaje powiadomienia (bo chce pdpatrzyc mechanizm powiadomien do mojego systemu). Tam jeszcze mozesz np. utworzyc komentarz i usunac go (tam jest taki x po prawej), albo edytowac (jest taki ołóweczek)

**Comment by szelma007** [comment]
dodanie tekstu po zablokowaniu
