### ISSUE TITLE
str. 14 notatka tworzenie

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#11]
sprawy - lista spraw - sprawa 1/2015

Edytuje Zadanie "Przygotowanie pytań do SIWS 
Tworzę notatkę przycisk "Nowa notatka" podaje tytuł i treść i używam przycisk "Utwórz"
Pojawia sie komunikat:

Wykryto 1 błąd na stronie

ORA-01400: cannot insert NULL into ("PRZ"."PRZ_POW"."ID") 
ORA-06512: at "PRZ.PRZ_NOTATKA_IOI_T", line 16 
ORA-04088: error during execution of trigger 'PRZ.PRZ_NOTATKA_IOI_T' 
ORA-06512: at "SYS.WWV_DBMS_SQL", line 1047 
ORA-06512: at "APEX_050000.WWV_FLOW_DYNAMIC_EXEC", line 889 
ORA-06512: at "APEX_050000.WWV_FLOW_DML", line 1671 
ORA-22816: unsupported feature with RETURNING clause

**Comment by baskap** [comment]
Do sprawdzenia jutro
