### ISSUE TITLE
str. 61 - strona www 

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#14]
Sprawy - Lista spraw - przycisk "Utwórz sprawę"

Wprowadzam adres strony (www.onet.pl) przechodzę dalej i tworzę sprawę. Na Liście spraw jeśli wybiorę link nie otwiera tej strony.

Jeśli wejdę w edycję sprawy (str. 3) dokonam zmian i dam "Zapisz zmiany" przy polu "Strona www" jest komunikat:
(Adres strony www sprawy musi zaczynać się od "http://" lub "https://")

**Comment by baskap** [comment]
Wymagam żeby wszystkie adresy stron się zaczynały od  "http://" lub "https://" - jak gdzieś tak nie ma to zmień

**Comment by szelma007** [comment]
może już przy tworzeniu i wprowadzaniu nowej sprawy mógłby sprawdzać i wymagać żeby adres strony zaczynały się od "http://" lub "https://")?

Sprawy - przycisk "Utwórz sprawę"

**Comment by baskap** [comment]
a spoko, racja :)
