### ISSUE TITLE
str. 3 - usunięcie sprawy

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#16]
sprawy - lista spraw - sprawa 3/2015

Wybieram "Edytuj sprawę" (po prawej stronie) i w ramce edycji daję "Usuń". 
Pojawia się komunikat:

ORA-01752: cannot delete from view without exactly one key-preserved table

**Comment by baskap** [comment]
Teraz nie ma możliwości usuwania z tego ekranu. Można sobie zmienić status na usunięta.
Bo generalnie robie tak, żeby nawet usunięte sprawy zostawały w bazie z możliwością przywrócenia i tylko były niewidoczne dla użytkownika.
