### ISSUE TITLE
str. 3 - usunięcie sprawy - potwierdzenie ang

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#17]
sprawy - lista spraw - sprawa 3/2015

Wybieram "Edytuj sprawę" (po prawej stronie) i w ramce edycji daję "Usuń". 

Pojawia się ramka potwierdzenia operacji po angielsku.

**Comment by baskap** [comment]
Tez powinno być jutro po polsku

**Comment by szelma007** [comment]
nie ma przycisku usuń
