### ISSUE TITLE
str. 62 i 63 nowa sprawa zapamiętywanie pól

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#19]
Utworzyłem sprawę wchodząc na Firmy - Slawek SWOlsztyn - Lista spraw - Utwórz sprawę.
 
Po utworzeniu sprawy ponownie przeszedłem na Firmy- Slawek SWOlsztyn - Lista spraw - "Utwórz sprawę".
Wypełniłem "Informacje o sprawie" przeszedłem do "Typ Sprawy i jest on już wypełniony.
Harmonogram sprawy również jest wypełniony.

**Comment by baskap** [comment]
Naprawione. A żeś to wyczaił to szacun :)
