### ISSUE TITLE
str.12 usuwanie użytkownika (potwierdzenie ang) i drugi komunikat

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#20]
Lista firm - Slawek - Szpital Wojewódzki Olsztyn / Jan Adamczek

Przy próbie usunięcia pracownika podaje komunikat potwierdzający po ang.

Jeśli dam Anuluj a następnie ponownie Usuń pojawi się komunikat:

Would you like to perform this delete action?
Zabroń tej stronie otwierać kolejne okna dialogowe

**Comment by baskap** [comment]
Ten drugi komunikat "Zabroń tej stronie otwierać kolejne okna dialogowe"  to jest z przeglądarki więc trzeba pozwolić otwierać i tyle

**Comment by baskap** [comment]
Would you like to perform this delete action?

Jutro powinno być po polsku.
