### ISSUE TITLE
str. 5 lista spraw na jednostce (np. księgowość)

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#26]
Firma - Lista firm - wybieram "Slawek - Szpital Wojewódzki Olsztyn" następnie z prawej stronu ze "struktury firmy" wybieram "Dział księgowości"

Przechodzę na zakładka "Lista spraw" i tworzę nową sprawę "Utwórz sprawę" 
W polu zamawiający pojawia się liczba "111164" i można utworzyć sprawę.

Jeśli założę sprawę to w Sprawy - lista spraw (str.2) jest ona widoczna (np. sprawa o nr 10/2015 - w kolumnie zamawiający ma "Dział księgowości).
Natomiast po wybraniu Firmy - Lista firm - Slawek - Szpital Wojewódzki Olsztyn - Dział księgowości ( str.5) i przejściu na zakładkę "Lista spraw" nie jest widoczna.

**Comment by baskap** [comment]
Teraz jak tworzysz sprawę z jakies jednostki to jako firma ustawia się nie podjednostka tylko główna firma
