### ISSUE TITLE
komentarz 3

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#3]
gggggggggggggggggg

**Comment by szelma007** [comment]
brak wpisanego tekstu

**Comment by szelma007** [comment]
tekst przy zamkniętym

**Comment by szelma007** [comment]
przy próbie usunięcia komentarza żąda potwierdzenia że usunąć

**Comment by szelma007** [comment]
pozostawiam otwartą

**Comment by baskap** [comment]
ggggg
