### ISSUE TITLE
str. 5 tworzenie nowej firmy

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#5]
(Lista firm - przycisk Utwórz) 

Pole "Kod pocztowy" może wprowadzić ograniczenie ilości znaków.

Pole "Skrót" jest pobierane do pola "jednostka" przy tworzeniu nowego pracownika (str. 12) i pola "Jednostka nadrzędna" przy tworzeniu nowej jednostki (str. 5). Jeśli podczas tworzenia nowej firmy pole "Skrót' pozostanie puste wówczas pojawia się napis "Firma".

Po wypełnieniu ramki "Dane Firmy" nie używam przycisku "Utwórz" tylko przechodzę do ramki "Lista spraw" i tworzę nową sprawę (przycisk - "Utwórz sprawę").
Firma w tej sytuacji nie jest zapisywana. 
Podczas normalnego tworzenia firmy przez przycisk "Utwórz" firma jest zakładana i pojawiają się kolejne ramki (Struktura firmy i Pracownicy firmy) może z ramką "Lista spraw" zrobić podobnie.

Na zakładce "Pracownicy firmy" napis jest podkreślony i powtórzony poniżej, a na "Liście spraw" podkreślony.

**Comment by baskap** [comment]
Kod pocztowy niech sobie zostanie tak jak jest.

Pole "Skrót" jest pobierane do pola "jednostka" przy tworzeniu nowego pracownika (str. 12) i pola "Jednostka nadrzędna" przy tworzeniu nowej jednostki (str. 5). Jeśli podczas tworzenia nowej firmy pole "Skrót' pozostanie puste wówczas pojawia się napis "Firma".

Tam jest specjalnie napis firma, bo czasami nazwy są bardzo długie i cięzko wybrać 
jeśli powiedzmy jest kilka stopni w hierarchii

**Comment by baskap** [comment]
Dwa następne są poprawione - sprawdź jutro
