### ISSUE TITLE
str.5 skrót jednostki podrzędnej

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#6]
wchodzę na listę firm wybieram do edycji "Slawek - szpital wojewódzki Olsztyn" w ramce "Struktura firmy" wybieram przycisk "Nowa jednostka" Wprowadzam np. "Dział gospodarczy"  i skrót "gospodarczy". Po użyciu przycisku "Utwórz" pole "skrót" nie jest zapisywany. Jeśli po raz drugi wprowadzę pole skrót i dam przycisk "Zachowaj zmiany" pole jest zapisywane.

**Comment by szelma007** [comment]
Podobnie jest przy zakładaniu "nowej firmy"

**Comment by baskap** [comment]
Do sprawdzenia jutro
