### ISSUE TITLE
str. 2 i 3 link

### ISSUE THREAD

**Issue by szelma007** [baskap/tender#9]
str. 2
Sprawy - lista spraw
W kolumnie link pojawia się napis "[Link]"

str. 3
Sprawy - lista spraw - edytuję sprawę (np. 125/lek/2015)
W pozycji link pojawia się napis "[Link]"

**Comment by baskap** [comment]
To specjalnie tak jest. Po kliknieciu na to ma sie otwierac strona przetargu - a sam aderes nie jest ważny dla kogos kto obsługuje sprawe a zabierał by dużo miejsca w tabeli. Na razie lik nie działa ale jutro juz powinien
